config/routes.rb
Rails.application.routes.draw do
  
  
  resources :stories do
  resources :votes do
  resource :session
  end	
  end	
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  validates :name, :link, presence: true
  has_many :votes do
  belongs_to :user	
    def latest
      order('id DESC').limit(3)
    end
    def to_param
    "#{id}-#{name.gsub(/\W/, '-').downcase}"
    end	
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
    has_many :stories
    has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@current_user = User.find_by(email: params[:email])
    if @current_user && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      redirect_to stories_path
    else
      render action: 'new'
    end
  end

  def destroy
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
 
  def index
  	@story = Story.order("RANDOM()").first
  end

  def new 
  @story = Story.new
  end

  def create
  	@story = Story.new(story_params)
  	if @story.save
    	flash[:notice] = "Story submission succeeded"
    	redirect_to stories_path
 	else
    	render action:'new'
  	end
  end

  def show
  	@story = Story.find(params[:id])
  end	
  
  private
  def story_params
  params.require(:story).permit(:name, :link)
  end

	

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
   def create
    @story = Story.find(params[:story_id])
    @story.votes.create
     respond_to do |format|
      format.html { redirect_to @story, notice: 'Vote was successfully created.' }
      format.js {}
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readit</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body><div id="content"> 
    
  <h1>Readit</h1>
  <% unless flash[:notice].blank? %>
    <div id="notification"><%= flash[:notice] %></div>
  <% end %>
  <%= yield %>
</div>
</html>

app/views/stories/create.js.erb
$("#vote_score").html("Score: " + <%= @story.votes.size %>)
$("#vote_score").css({backgroundColor: "#ffffcc"});
setTimeout(function(){
  $("#vote_score").css({backgroundColor: "#ffffff"});
}, 2000);
$("#vote_history").html('<%= j( render partial: "votes/vote", collection: @story.votes.latest )  %>');

app/views/stories/index.html.erb
<%= link_to @story.name, story_path(@story) %>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
  <div class="form_errors">
    <h3>Errors</h3>
    <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @story do |f| %>
  <div>
    <p><%= f.label :name  %></p>
    <%= f.text_field :name %>
  </div>
  <div class="field_with_errors">
  <label for="story_link">Link</label>
</div>
<div class="field_with_errors">
  <input type="text" value="" name="story[link]" id="story_link">
</div>
  <%= submit_tag %>
<% end %>

app/views/stories/show.html.erb
<h2>
  <span id="vote_score">
    Score: <%= @story.votes.size %>
  </span>
  <%= @story.name %>
</h2>
<ul id="vote_history">
  <% if @story.votes.empty? %>
    <em>No votes yet!</em>
  <% else %>
    <%= render partial:'votes/vote',
        collection: @story.votes.latest %>
  <% end %>
</ul>
<p>
  <%= link_to @story.link, @story.link %>
</p>
<div id="vote_form">
  <%= form_for [ @story, Vote.new ], remote: true do |f| %>
    <%= f.submit 'Vote for it' %>
  <% end %>
</div>

app/views/votes/_vote.html.erb
<li><%= vote.created_at.to_formatted_s(:short) %></li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>